Add the conection with Sequelize and others configurations of package.json
DevKike/todo_list_node pull request #4
Opened 2023-12-05 19:45 UTC by DevKike

I haven't installed the package for the tests yet, but there I have the folder with the file

2023-12-05 19:52 UTC, Cbermudez98 requested changes

2023-12-05 19:52 UTC, Cbermudez98 commented on src/index.js
> +const port = process.env.PORT || 3000;
Si vas a usar variables de entorno, tienes que instalar este paquete [dotenv](https://www.npmjs.com/package/dotenv) y crear el archivo .env en la raiz del proyecto

2023-12-05 19:52 UTC, Cbermudez98 commented on src/index.js
> +  console.log(`Server running in port ${port}`);
Buen uso del literal string :heart:

2023-12-05 21:12 UTC, DevKike commented on src/index.js
> +const port = process.env.PORT || 3000;
como se borró lo olvidé 😔

2023-12-06 04:55 UTC, Cbermudez98 requested changes

2023-12-06 04:55 UTC, Cbermudez98 commented on src/modules/user/controller/user.controller.js
module.exports, tiene que ser module.exports = {createUser}, ya que tu tienes que crear varias funciones y exportarlas para que el router pueda acceder a ellas, [formas de exportar en node.js](https://www.sitepoint.com/understanding-module-exports-exports-node-js/)

2023-12-06 04:55 UTC, Cbermudez98 commented on src/index.js
> +const port = process.env.PORT || 3000;
Se evidencia que resolvio la peticion de cambio

2023-12-10 04:37 UTC, DevKike commented on src/modules/user/controller/user.controller.js
Fixed.

2023-12-10 04:39 UTC, Cbermudez98 approved these changes
LGTM!!!!! :ok_hand: good work

2023-12-10 04:39 UTC, merged